oidc-authservice:
  env:
    - name: AUTHSERVICE_URL_PREFIX
      value: ${AUTHSERVICE_URL_PREFIX}
    - name: OIDC_PROVIDER
      value: ${OIDC_PROVIDER}
    - name: OIDC_AUTH_URL
      value: ${OIDC_AUTH_URL}
    - name: OIDC_AUTHSERVICE_IMAGE
      value: ${OIDC_AUTHSERVICE_IMAGE}
    - name: OIDC_SCOPES
      value: ${OIDC_SCOPES}
    - name: REDIRECT_URL
      value: ${REDIRECT_URL}
    - name: SKIP_AUTH_URI
      value: ${SKIP_AUTH_URI}
    - name: USERID_HEADER
      value: "kubeflow-userid"
    - name: USERID_CLAIM
      value: "email"
    - name: Preferred_Username
      value: "preferred_username"
    - name: PORT
      value: "'8080'"
    - name: STORE_PATH
      value: "/var/lib/authservice/data.db"
    - name: CLIENT_ID
      value: ${CLIENT_ID}
    - name: CLIENT_SECRET
      value: ${CLIENT_SECRET}
