apiVersion: v2
name: test
description: A Parent Helm chart for Kubernetes
type: application
# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates
version: 0.1.0

dependencies:
  - name: oidc-authservice
    version: 0.1.0
    repository: file://charts/common/oidc-authservice
  - name: kubeflow-namespace
    version: 0.1.0
    repository: file://charts/common/kubeflow-namespace


