apiVersion: v1
data:
  OIDC_PROVIDER: {{ .Values.OIDC_PROVIDER }}
  OIDC_AUTH_URL: {{ .Values.OIDC_AUTH_URL }}
  OIDC_SCOPES: {{ .Values.OIDC_SCOPES }}
  PORT: {{ .Values.PORT }}
  REDIRECT_URL: {{ .Values.REDIRECT_URL }}
  STORE_PATH: /var/lib/authservice/data.db
  SKIP_AUTH_URI: {{ .Values.SKIP_AUTH_URI }}
  USERID_CLAIM: {{ .Values.USERID_CLAIM }}
  USERID_HEADER: {{ .Values.USERID_HEADER }}
  USERID_PREFIX: ''
  Preferred_Username: {{ .Values.Preferred_Username }}

kind: ConfigMap
metadata:
  name: oidc-authservice-parameters
  namespace: istio-system